#!/bin/python

import os

## Just the directory on bluepebble used for this analysis
wd = os.getcwd()
ARIES_DATA_DIR=""
METHODS = ["celldmc", "tca", "tcareg", "omicwas", "toast"]
SPLIT = list(range(1, 101))

rule all:
    input:
        wd + "/data/aries_fom.RData", 
        expand(wd + "/results/temp/{method}_res_split{split}.RData", method = METHODS, split = SPLIT), 
        wd + "/results/false-positives-plot.pdf"

rule clean_meth:
    input:
        script = wd + "/scripts/clean-meth.R", 
        meth = ARIES_DATA_DIR + "/methylation/aries-v4/aries-meth-v4.Robj", 
        samplesheet = ARIES_DATA_DIR + "/methylation/aries-v4/aries-samplesheet.Robj", 
        detp = ARIES_DATA_DIR + "/methylation/aries-v4/aries-detp-v4.Robj",
    output:
        wd + "/data/aries_fom.RData",
    shell:
        'echo $HOSTNAME; Rscript {input.script} "{input.meth}" "{input.samplesheet}" "{input.detp}" "{output}"'


# rule install_pkgs:
#     input:

rule sims:
    input:
        script = wd + "/scripts/test-methods.R", 
        meth = wd + "/data/aries_fom.RData", 
        cc = ARIES_DATA_DIR + "/methylation/aries-v4/aries-blood-cell-counts.txt",
    output:
        wd + "/results/temp/{method}_res_split{split}.RData"
    shell:
        'echo $HOSTNAME; Rscript {input.script} "{input.meth}" "{input.cc}" "{output}"'

rule sims_res:
    input:
        script = wd + "/scripts/test-methods-results.R", 
        inputs = expand(wd + "/results/temp/{method}_res_split{split}.RData", method = METHODS, split = SPLIT)
    output:
        fp = wd + "/results/false-positives-plot.pdf", 
        lamb = wd + "/results/lambdas-plot.pdf", 
        fp_lamb = wd + "/results/false-positives-and-lambdas-plot.pdf"
    shell:
        'echo $HOSTNAME; Rscript {input.script} "{output.fp}" "{output.lamb}" "{output.fp_lamb}"'


